### ISSUE TITLE
As a user, I need a basic YouTube client

### ISSUE THREAD

**Issue by labofoz** [BrowseHandsfree/BrowseHandsfree.com#4]
![image](https://user-images.githubusercontent.com/48814430/56936229-13769080-6aab-11e9-8b02-cb92c6685019.png)

## Scope

- [x] Add a YouTube link to **(A)** that will route to /youtube
- [x] Show a list of videos in **(B)**
- [x] Clicking on a video in **(B)** should open up /youtube/:videoID
- [x] Start/Stop the video
- [x] Scrub the video
- [x] Show video comments
- [x] Show video meta

## Tasks
- [x] Move sidebar into it's own component
- [x] Install Vuex
- [x] Move states into store
- [x] Make sidebar collapsible
- [x] Install vue-routers
- [x] Create a /home route
- [x] Create the /youtube route

**Comment by labofoz** [comment]
Finished!

![](https://media.giphy.com/media/ekH6EPOKCA5bSPpECA/giphy.gif)
